// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo2Zx287QXfM-YaB2lHcXPjllM0SMjGGg',
    appId: '1:277464278163:web:9ac8c6ab9b8f54e7e35966',
    messagingSenderId: '277464278163',
    projectId: 'my-musico-app-0101',
    authDomain: 'my-musico-app-0101.firebaseapp.com',
    storageBucket: 'my-musico-app-0101.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQDeZanJtDSysED1FnGwMZtXTtAoC2zTQ',
    appId: '1:277464278163:android:412815c890aca1a1e35966',
    messagingSenderId: '277464278163',
    projectId: 'my-musico-app-0101',
    storageBucket: 'my-musico-app-0101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArwnI_KRcbIEb8w9ioLL0K2SfLRbXL6o0',
    appId: '1:277464278163:ios:36619dce9ea8fb4de35966',
    messagingSenderId: '277464278163',
    projectId: 'my-musico-app-0101',
    storageBucket: 'my-musico-app-0101.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArwnI_KRcbIEb8w9ioLL0K2SfLRbXL6o0',
    appId: '1:277464278163:ios:36619dce9ea8fb4de35966',
    messagingSenderId: '277464278163',
    projectId: 'my-musico-app-0101',
    storageBucket: 'my-musico-app-0101.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo2Zx287QXfM-YaB2lHcXPjllM0SMjGGg',
    appId: '1:277464278163:web:39ffb9884da40803e35966',
    messagingSenderId: '277464278163',
    projectId: 'my-musico-app-0101',
    authDomain: 'my-musico-app-0101.firebaseapp.com',
    storageBucket: 'my-musico-app-0101.firebasestorage.app',
  );
}
